### PR TITLE
Update 'libusb' to 1.0.23

### PR DESCRIPTION
**Pull request by themarpe**
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html)
  step by step carefully. **Yes**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/themarpe/hunter-testing/builds/33550597
  * https://travis-ci.com/github/themarpe/hunter-testing/builds/171587229

---

This pull request adds latest (1.0.23) libusb library. It also fixes some options regarding schema usage, so custom flags can be passed to ./configure script. The documentation adds a way to build this package without the udev support which in turn doesn't require libudev-dev package. 

I don't know how severe the drawbacks are in case of lacking udev support, might do a pull request for udev in future, so that *Pitfalls* can be eliminated from this package.

### CODE REVIEW

**Comment by rbsheth** [comment]
Hi @themarpe, can you fix the spell check errors? See https://hunter.readthedocs.io/en/latest/creating-new/create/cmake.html?highlight=spelling#add-documentation

**Comment by themarpe** [comment]
@rbsheth thanks for letting me know regarding spellchecking. Fixed:)

**Comment by rbsheth** [comment]
> @rbsheth thanks for letting me know regarding spellchecking. Fixed:)

Thanks for fixing!

**Comment by rbsheth** [comment]
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.23.259

**Pull request merged**
