### PR TITLE
Add support to use cmake package configuration file from boost

### PR DESCRIPTION
**Pull request by Bjoe**
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html)
  step by step carefully. **Yes**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/Bjoe/hunter-t1t06/builds/30740305
  * https://travis-ci.org/Bjoe/hunter/builds/649294215

### CODE REVIEW

**Comment by Bjoe** [comment]
This PR introduced the possibility to use the cmake config module provided from the boost project.
It is optional and can be enabled via hunter_config. Add as `CMAKE_ARGS`  [USE_CONFIG_FROM_BOOST=ON](https://github.com/cpp-pm/hunter/blob/30882c2ca42f53bd9e95cbc1ca2147789633b336/examples/Boost-log/config.cmake#L3)

That has the advantage that the "user" does not need to know which dependency for example boost::log needs. See the difference in the diff https://github.com/cpp-pm/hunter/pull/154/files#diff-20118a896da0e1fbefa637e8075cb6fa

It will also solve a potential problem that the [BoostConfig from hunter is using FindBoost](https://github.com/cpp-pm/hunter/blob/e0b69021ecb3849cbcccc309f9e8b266be9f77b1/cmake/templates/BoostConfig.cmake.in#L51) see #139

**Comment by Bjoe** [comment]
Btw. this PR needs the PR from #140

**Comment by daminetreg** [comment]
> That has the advantage that the "user" does not need to know which dependency for example boost::log needs. See the difference in the diff https://github.com/cpp-pm/hunter/pull/154/files#diff-20118a896da0e1fbefa637e8075cb6fa
> 

Note that this isn't fully true, you just need a cmake version that knows about the Boost version and then it automatically adds the knowledge of what you need to link transitively. It doesn't know when cmake is older than boost.

But clearly it's better to trust boost whenever everything works fine. The problem is mostly for me the static vs shared strategy that we should get changed.

**Comment by Bjoe** [comment]
@daminetreg Yep I know, but hunter introduced its own [FindBoost.cmake](https://github.com/cpp-pm/hunter/blob/e0b69021ecb3849cbcccc309f9e8b266be9f77b1/cmake/find/FindBoost.cmake) and it is not well maintained ...

@daminetreg Did you know why in hunter is a [FindBoost.cmake](https://github.com/cpp-pm/hunter/blob/e0b69021ecb3849cbcccc309f9e8b266be9f77b1/cmake/find/FindBoost.cmake)?

**Comment by Bjoe** [comment]
@daminetreg Maybe you can update this FindBoost.cmake in hunter in your PR #140 ?

**Comment by daminetreg** [comment]
> @daminetreg Yep I know, but hunter introduced its own [FindBoost.cmake](https://github.com/cpp-pm/hunter/blob/e0b69021ecb3849cbcccc309f9e8b266be9f77b1/cmake/find/FindBoost.cmake) and it is not well maintained ...
> 

Oh 😨 Thanks for noticing, I didn't remember that.

> @daminetreg Did you know why in hunter is a [FindBoost.cmake](https://github.com/cpp-pm/hunter/blob/e0b69021ecb3849cbcccc309f9e8b266be9f77b1/cmake/find/FindBoost.cmake)?

 I think he might have updated based on the version of Boost @ruslo integrated but I'm unsure. I'll try to find the common ancestor in cmake repository in the times he added the "fixed" FindBoost to see what changes he operated.

> @daminetreg Maybe you can update this FindBoost.cmake in hunter in your PR #140 ?

If I can I'll make a separate PR for this, because it's better to have what we have now, than to extend the scope infinitely of this PR.

**Comment by rbsheth** [comment]
@Bjoe #140 is merged, do you need to update this one?

**Comment by Bjoe** [comment]
> @Bjoe #140 is merged, do you need to update this one?

@rbsheth Yep. I will do this  .... give me some time

**Comment by BenWhetton** [comment]
Does anybody know hunter maintains a fork of FindBoost.cmake? It seems like something that should be understood before bolting on more complexity to work around it?

**Comment by Bjoe** [comment]
@BenWhetton `FindBoost.cmake` in hunter was introduced four years ago ... I'm not sure what you mean with bolting on more complexity to work around it?

Again my idea is to use the BoostConfig from boost so that BoostConfig and FindBoost from hunter is not anymore used ... in my opinion it is lesser complexity and lesser maintained stuff in hunter ...

**Comment by Bjoe** [comment]
Btw. since I merge latest master and introduced a USE_CONFIG_FROM_BOOST 1f1e729 ... it unfortunately not working very well. If you want to have a successful test with BoostConfig from boost, then use this commit 14eb85c ...

I'm working on a proper solution to have both approaches in hunter ...

**Comment by Bjoe** [comment]
Sorry, [this problem that I mentioned above](https://github.com/cpp-pm/hunter/pull/154#issuecomment-588090679) was only a local issue. 1f1e729 is absolutely working correctly.

See also Travis/AppVeyor test builds:

* https://travis-ci.org/Bjoe/hunter/builds/651109326
* https://ci.appveyor.com/project/Bjoe/hunter-tdmm2/builds/30863221


Please test/give it a try and give your opinion

This is the hunter "version config" to test:

    HunterGate(
        URL "https://github.com/Bjoe/hunter/archive/1f1e7295e026b5b6bdf6122a98d36d521fff1dbb.zip"
        SHA1 "69417c1d41f39be07465dc57e115ef97b2c648f2"
        LOCAL
    )

Add in the `[YOUR_PROJECT_SRC_DIR]/cmake/Hunter/config.cmake`:

    hunter_config(Boost VERSION 1.72.0-p0 CMAKE_ARGS USE_CONFIG_FROM_BOOST=ON)

**Comment by rbsheth** [comment]
> Should I add some "new tests" or "take only some tests"?

What do you mean by this? If you want to test both the old and new behavior, you can add some new tests for this flag.

**Comment by BenWhetton** [comment]
> @BenWhetton `FindBoost.cmake` in hunter was introduced four years ago ... I'm not sure what you mean with bolting on more complexity to work around it?
> 
> Again my idea is to use the BoostConfig from boost so that BoostConfig and FindBoost from hunter is not any more used (maybe remove it) ... in my opinion it is lesser complexity and lesser maintained stuff in hunter ...

I believe this solution will not work for previous versions of Boost where there is no CMake support so it is not a full solution to #141.

**Comment by Bjoe** [comment]
@BenWhetton Yep absolutely right, that's why I added a Boost version check ... for example https://github.com/cpp-pm/hunter/blob/b2bd8aec97e9ef3c6aa1808ebd2ec5188eb1cdaa/cmake/projects/Boost/schemes/url_sha1_boost.cmake.in#L168 and https://github.com/cpp-pm/hunter/blob/b2bd8aec97e9ef3c6aa1808ebd2ec5188eb1cdaa/cmake/projects/Boost/hunter.cmake#L428

As I said ... maybe we can remove it .... but I think it is not yet possible to remove it because it has to be backward compatible ....

Sometimes I think, maybe it is better to create a new "Boost" package with boost config support? It is maybe lesser to "maintain"/ better to understand? But I don't know if the "community"/user will understands this?

**Comment by Bjoe** [comment]
@rbsheth Ok, I added some new tests: Boost-useBoostConfig, Boost-filesystem-useBoostConfig, Boost-iostream-useBoostConfig, Boost-chrono-useBoostConfig and Boost-log-useBoostConfig

Here is the links to the Travis/AppVeyor with status "All passed":
* https://travis-ci.org/Bjoe/hunter/builds/654740864
* https://ci.appveyor.com/project/Bjoe/hunter-tdmm2/builds/31034850

I think I should add a comment in the Boost.rst .... I will do this next days...

**Comment by Bjoe** [comment]
Ok, I added a hint about ``USE_CONFIG_FROM_BOOST`` in the boost doc (Boost.rst)

So I'm done ...
Let's review/discuss/test :-)

Discussable is maybe that approach in [hunter.cmake line 428 - 448](https://github.com/cpp-pm/hunter/blob/4187249b2a5e5ba233bcb9eb11e8b93356ae628f/cmake/projects/Boost/hunter.cmake#L428) to set the package configuration options for the boost package configuration file.

**Comment by rbsheth** [comment]
@Bjoe Do you think this is ready for merge?

**Comment by Bjoe** [comment]
All test`s are green:

With enabled `USE_CONFIG_FROM_BOOST`
* https://ci.appveyor.com/project/Bjoe/hunter-t1t06/builds/30740305
* https://travis-ci.org/Bjoe/hunter/builds/649294215

Without enabled `USE_CONFIG_FROM_BOOST`
* https://travis-ci.org/Bjoe/hunter/builds/654740864
* https://ci.appveyor.com/project/Bjoe/hunter-tdmm2/builds/31034850

So from my side it looks fine.

It would be great if someone else can test this also ... or you wait until I test that in my company where we build a project for iOS, Android, linux, Windows and macOS.....

**Pull request merged**
