### PR TITLE
Add sqlite3 to the database page

### PR DESCRIPTION
**Pull request by jamiecook**
Updating the documentation to add sqlite to db section

### CODE REVIEW

**Comment by NeroBurner** [comment]
LGTM

**Comment by jamiecook** [comment]
What's going on github? 
image

**Comment by jamiecook** [comment]
It looks like github was having some issues yesterday (I also noticed this when using cmake to download binaries for another package from there) - I'm pushing a whitespace change to trigger another build and see if it's resolved.

**Comment by jamiecook** [comment]
And that seems to have fixed it

**Comment by jamiecook** [comment]
@NeroBurner  - is there anything else I can do to help get this merged?

**Comment by NeroBurner** [comment]
I can't merge, I'm just an interested user of `hunter`

@rbsheth could merge it

**Pull request merged**
