### PR TITLE
Revert "Add 'tiny-process-library' package"

### PR DESCRIPTION
**Pull request by rbsheth**
Reverts cpp-pm/hunter#98, since it uses a FindPackage module instead of CMake targets. @Bjoe @bkotzz

### CODE REVIEW

**Comment by Bjoe** [comment]
Can you create an upstream project from https://gitlab.com/eidheim/tiny-process-library into cpp-pm? Than I can quickly fix remove the FindPackage module.

**Comment by rbsheth** [comment]
@Bjoe Done, here it is: https://github.com/cpp-pm/tiny-process-library

**Comment by Bjoe** [comment]
Ok done. See PR https://github.com/cpp-pm/tiny-process-library/pull/1

**Comment by Bjoe** [comment]
I created a new pull request .... https://github.com/cpp-pm/hunter/pull/102

**Comment by rbsheth** [comment]
Closing in favor of #102

**Pull request closed without merging**
