### PR TITLE
add command and options to compile with emscripten

### PR DESCRIPTION
**Pull request by Dargun**
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/create/cmake.html)
  step by step carefully. **[Yes|No]**

* My change will allow compile OPENSSL with [emscripten-cxx14.cmake](https://github.com/ruslo/polly/blob/master/emscripten-cxx14.cmake)

---

* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html)
  step by step carefully. **[Yes}**

---

* I've checked this [Git style guide](https://0.readthedocs.io/en/latest/git.html). **[Yes}**
* I've checked this [CMake style guide](https://0.readthedocs.io/en/latest/cmake.html). **[Yes}**
* My change will work with CMake 3.2 (minimum requirement for Hunter). **[Yes|No]**
* I will try to keep this pull request as small as possible and will try not to mix unrelated features. **[Yes}**

---

### CODE REVIEW

**Review by NeroBurner — APPROVED** [review]
LGTM

**Comment by Dargun** [comment]
seems there are some test in general failing or has that todo with my change?

**Comment by NeroBurner** [comment]
From https://cpp-pm.github.io/hunter/ it seems the nmake and ninja builds were skipped (marked blue). Only the VS16 windows build was reliably working (and still does work)

test matrix OpenSSL

The failing pipelines are related to VS16 with nmake and ninja, as well as mingw builds on Windows. It doesn't look like your change did that. I assume the schema for OpenSSL needs to be updated to handle the new compiler/environments

failing vs16 tests

**Comment by NeroBurner** [comment]
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.24.4

**Pull request merged**
