### PR TITLE
Update zstd to v1.5.0.

### PR DESCRIPTION
**Pull request by ned14**
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html)
  step by step carefully. **Yes**

### CODE REVIEW

**Comment by ned14** [comment]
Re: the /analyze failure, I will report it upstream if it repros on their trunk, but I'm unsure what to do with this release?

**Comment by ned14** [comment]
@rbsheth What would you prefer I do re the analyse failure above? Note we're using the zstd 1.5.0 release directly, no local fork.

**Comment by rbsheth** [comment]
> @rbsheth What would you prefer I do re the analyse failure above? Note we're using the zstd 1.5.0 release directly, no local fork.

Typically, we don't care too much about the analyze failure.

**Review by rbsheth — APPROVED** [review]

**Comment by rbsheth** [comment]
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.23.319

**Pull request merged**
