### PR TITLE
Add various recent LLVM versions

### PR DESCRIPTION
**Pull request by mrexodia**
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html)
  step by step carefully. **Yes**

---

### CODE REVIEW

**Comment by rbsheth** [comment]
@mrexodia Can you please bump the version here too? https://github.com/cpp-pm/hunter/blob/master/cmake/configs/default.cmake#L90

Thanks!

**Comment by mrexodia** [comment]
> @mrexodia Can you please bump the version here too? https://github.com/cpp-pm/hunter/blob/master/cmake/configs/default.cmake#L90
> 
> Thanks!

Sure, will do it later today.

**Comment by rbsheth** [comment]
@mrexodia friendly *ping*

**Comment by mrexodia** [comment]
Thanks, done ^^

**Comment by apivovarov** [comment]
Looks like Hunter project is dead....

**Comment by rbsheth** [comment]
> Looks like Hunter project is dead....

Wouldn't say _dead_, but I definitely don't have the time I used to for Hunter. @NeroBurner has been helping a lot.

**Pull request merged**
