### PR TITLE
Update fmt package to 9.1.0

### PR DESCRIPTION
**Pull request by apivovarov**
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html)
  step by step carefully. **[Yes]**

I used prev [PR-514](https://github.com/cpp-pm/hunter/pull/514) as an example

## Testing
Tested new `fmt-9.1.0` with existing `spdlog-1.9.2-p0` in one project - everything is OK.

### CODE REVIEW

**Comment by apivovarov** [comment]
@erickguan  Can you look at `fmtexample.cpp` fixes?

**Comment by apivovarov** [comment]
CI / fmt osx-10-15-make-cxx14 macos-10.15 job did not start? @rbsheth @NeroBurner can you check github CI?

**Comment by rbsheth** [comment]
Looks like it isn't working for some reason. Else things look good.

**Comment by erickguan** [comment]
@apivovarov Sorry for being late. Solid reasoning and comment. Well done.

**Comment by NeroBurner** [comment]
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.25.0

**Pull request merged**
