### PR TITLE
Add 'opusfile' package

### PR DESCRIPTION
**Pull request by drodin**
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/create/cmake.html)
  step by step carefully. **Yes**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/drodin/hunter/builds/34670772
  * https://travis-ci.com/github/drodin/hunter/builds/179816505

* I have submitted CI configs to https://github.com/cpp-pm/hunter-testing targeting `pkg.template` branch,
  see this merged pull request https://github.com/cpp-pm/hunter-testing/pull/72

* Depends on https://github.com/cpp-pm/hunter/pull/245

* Need a fork of https://github.com/xiph/opusfile in https://github.com/cpp-pm

### CODE REVIEW

**Comment by rbsheth** [comment]
@drodin https://github.com/cpp-pm/opusfile

**Comment by drodin** [comment]
done

**Comment by rbsheth** [comment]
@drodin I left a comment in the repo, you need to update the version of Hunter to include the Opus project (so v0.23.265)

**Comment by rbsheth** [comment]
@drodin I left a comment in the repo, you need to update the version of Hunter to include the Opus project (so v0.23.265)

**Comment by drodin** [comment]
> @drodin I left a comment in the repo, you need to update the version of Hunter to include the Opus project (so v0.23.265)

@rbsheth see https://github.com/cpp-pm/opusfile/pull/1

**Comment by rbsheth** [comment]
@drodin Thanks! https://github.com/cpp-pm/opusfile/releases/tag/v0.12-p0

**Comment by drodin** [comment]
@rbsheth updated

**Review by rbsheth — APPROVED** [review]

**Comment by rbsheth** [comment]
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.23.266

**Pull request merged**
