### PR TITLE
Do not build tests in date library

### PR DESCRIPTION
**Pull request by kaihowl**
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html)
  step by step carefully. **Yes**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/kaihowl/hunter/builds/30044220
     * Last config is broken. Checking what is wrong there.
     * This is already broken without my changes. Proof: https://ci.appveyor.com/project/kaihowl/hunter/builds/30044401
  * https://travis-ci.com/kaihowl/hunter/builds/143998584

### CODE REVIEW

**Comment by kaihowl** [comment]
Since the cxx17 vs2015 toolchain is already broken on master, I would exclude this toolchain. I am not sure if the following build error is a source code problem or a toolchain problem. Input appreciated. 
```
 50%] Building CXX object CMakeFiles/tz.dir/src/tz.cpp.o
/C/msys64/usr/bin/g++.exe  -DHAS_REMOTE_API=0 -DUSE_AUTOLOAD=0 @CMakeFiles/tz.dir/includes_CXX.rsp -std=c++17 -O3 -DNDEBUG   -std=c++17 -o CMakeFiles/tz.dir/src/tz.cpp.o -c /C/projects/hunter/_testing/Hunter/_Base/4b67acc/4f4f593/cbc5d16/Build/date/Source/src/tz.cpp
/C/projects/hunter/_testing/Hunter/_Base/4b67acc/4f4f593/cbc5d16/Build/date/Source/src/tz.cpp: In member function 'const date::time_zone* date::tzdb::current_zone() const':
/C/projects/hunter/_testing/Hunter/_Base/4b67acc/4f4f593/cbc5d16/Build/date/Source/src/tz.cpp:3674:17: error: 'readlink' was not declared in this scope
 3674 |             if (readlink(timezone, rp, sizeof(rp)-1) > 0)
      |                 ^~~~~~~~
/C/projects/hunter/_testing/Hunter/_Base/4b67acc/4f4f593/cbc5d16/Build/date/Source/src/tz.cpp:3702:17: error: 'readlink' was not declared in this scope
 3702 |             if (readlink(timezone, rp, sizeof(rp)-1) > 0)
      |                 ^~~~~~~~
make[5]: Leaving directory '/c/projects/hunter/_testing/Hunter/_Base/4b67acc/4f4f593/cbc5d16/Build/date/Build/date-Release-prefix/src/date-Release-build'
```

**Comment by kaihowl** [comment]
Furthermore, do I need to set a new version with `-p1` additionally as a suffix? I have not done a bug fix update to a package, yet.

**Comment by rbsheth** [comment]
@kaihowl For a patch, we need a new fork. Looking at the upstream codebase, it seems like tests are not built by default?

**Comment by kaihowl** [comment]
Upstream builds the tests by default. See https://github.com/HowardHinnant/date/blob/e7e1482087f58913b80a20b04d5c58d9d6d90155/CMakeLists.txt#L15 for the option that is per default on. 

Since this is a CMake option I don’t think a fork is necessary. Just setting the cmake arg as the default argument for the package should do the trick. Or not?

**Comment by rbsheth** [comment]
Yes, your proposed change should be sufficient. Are you still working on the vs2015 fix?

**Comment by kaihowl** [comment]
I did not have time to revisit the fix yet. I will create a PR to exclude the toolchain this week.

**Comment by kaihowl** [comment]
I had some time and created the PR on hunter-testing to update the toolchain. See https://github.com/cpp-pm/hunter-testing/pull/40.

I have updated my testing branch based on https://github.com/cpp-pm/hunter-testing/pull/40 and merged in this PR. The results can be found on (still running):

- https://ci.appveyor.com/project/kaihowl/hunter/builds/30141375
- https://travis-ci.com/kaihowl/hunter/builds/144593692

**Pull request merged**
