### PR TITLE
[docs] Make Hunter and CMake versions consistent

### PR DESCRIPTION
**Pull request by SamuelMarks**

### CODE REVIEW

**Comment by NeroBurner** [comment]
Awesome, good job

Did you make all those changes by hand?

**Comment by SamuelMarks** [comment]
@NeroBurner Partially. Used [`rg`](https://github.com/BurntSushi/ripgrep) to find the issues, sometimes [`fastmod`](https://github.com/facebookincubator/fastmod) to apply fixes, and other times by hand. Now that it's all internally consistent it should be trivially to update in every place on release using pure `sed` (or `fastmod`… which I prefer for recursive application and that it has a `-F` argument… also it's cross-platform).

**Comment by NeroBurner** [comment]
thanks for the explanation! And once again great job

**Review by rbsheth — APPROVED** [review]
Thank you!

**Comment by rbsheth** [comment]
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.23.298

**Pull request merged**
