### PR TITLE
Update 're2' to 2023.09.01

### PR DESCRIPTION
**Pull request by hjmallon**
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html)
  step by step carefully. **[Yes]**

### CODE REVIEW

**Comment by rbsheth** [comment]
Can you check on the CI runs?

**Comment by hjmallon** [comment]
Useful spot from the CI, re2 has introduced an abseil dependancy. I guess it must be picking one up from my local env automatically. I will close this PR.

**Comment by rbsheth** [comment]
@hjmallon Thanks for your contributions! Perhaps we can introduce the abseil dependency through Hunter and update re2?

**Comment by hjmallon** [comment]
Yeah I guess it would need a fork of re2? Unless there are some cleverer forkless Hunter things possible now?

**Comment by NeroBurner** [comment]
Wanted to fork it for you, but there already is one, probably old, but exists already: https://github.com/cpp-pm/re2/

**Comment by hjmallon** [comment]
Thanks, to be honest I'm in no great need of new re2 (we only use it inside grpc) so I'm not going to get to this soon.

**Comment by NeroBurner** [comment]
latest upstream tag now also available as https://github.com/cpp-pm/re2/releases/tag/2023-09-01

if you get around to it. Hunterizing should be easy as the project already creates the `re-config.cmake` files itself. So only HunterGate and `hunter_add_package()` should be needed

**Pull request closed without merging**
