### PR TITLE
Pullrequest

### PR DESCRIPTION
**Pull request by CarloWood**
These are four commits that I needed to get,
1) submodules inside submodules working
2) fix not having a hunter_add_package in the root projects CMakeLists.txt
3) some extra debug messages for easier diagnostics

### CODE REVIEW

**Comment by Bjoe** [comment]
Hi @CarloWood ... your "Pullrequest" sound interesting. Has this something to do with if I have "add" a third party lib based on cmake build to easily add "dependencies"? Maybe you can be little bit more "verbose"?

**Comment by CarloWood** [comment]
@Bjoe No, this is just something everyone wants and needs (who uses git submodules). I wonder why it wasn't merged into hunter yet *sigh*. I once wrote awesome and complete fixes for everything multi-monitor for a window manager - then kept updating the patches for several YEARS so they'd still merge... and then gave up. Hope this isn't one of those projects.

**Comment by rbsheth** [comment]
Closing after months of inactivity. Feel free to open again.

**Comment by CarloWood** [comment]
Yeah, I gave up on hunter a while ago. Since it is based internally on tar balls and implements git "support" through "git archive" that loses all and any submodule information, it is unusable for me.

I've been writing my own version of 'hunter' from scratch.

**Pull request closed without merging**
