### PR TITLE
fix for 'Ninja Multi-Config' generator

### PR DESCRIPTION
**Pull request by mean-ui-thread**
* I've checked this [Git style guide](https://0.readthedocs.io/en/latest/git.html). **Yes**
* I've checked this [CMake style guide](https://0.readthedocs.io/en/latest/cmake.html). **Yes**
* My change will work with CMake 3.2 (minimum requirement for Hunter). **Yes**
* I will try to keep this pull request as small as possible and will try not to mix unrelated features. **Yes**

### CODE REVIEW

**Comment by mean-ui-thread** [comment]
yes I am aware that `Ninja Multi-Config` has been added since cmake 3.17 and Hunter has to support cmake 3.2. However, since my change only compares generator strings that simply cannot occur in cmake 3.2, my propose change should cause no harm to the oldest cmake versions that hunter must maintain.

**Comment by NeroBurner** [comment]
Thanks for this improvement. Will this flag be set always when using Ninja generator, or does one need to explicitly enable this ninja-multi-config generator?

**Comment by mean-ui-thread** [comment]
> Thanks for this improvement. Will this flag be set always when using Ninja generator, or does one need to explicitly enable this ninja-multi-config generator?

The latter: One does need the explicitly enable the ninja multi-config generator. Example:
```
cmake -G "Ninja Multi-Config" -B build/ninja-multi-config/ .
```

So far it seems to work with ninja multi-config except when building for `--config RelWithDebInfo` or `--config MinSizeRel` but I believe it is a known limitation with hunter's current implementation that may also impacts xcode and visual studio (I need to confirm this). Hunter only produces Debug and Release binaries. If hunter with ninja-multi-config needs to work with RelWithDebInfo or MinSizeRel (by linking the regular release binaries in hunter's cache) please let me know and I will look into it (it can be done in a separate PR too if that is okay with you)

**Comment by NeroBurner** [comment]
Thanks for the clarification. The changes seem minimal, so @rbsheth please merge.

Yes, `Release,Debug` are the default build types built by hunter. But you can override this with a toolchain file defining the variable [HUNTER_CONFIGURATION_TYPES](https://hunter.readthedocs.io/en/latest/reference/user-variables.html#hunter-configuration-types)

**Comment by mean-ui-thread** [comment]
@NeroBurner good to know! Thanks!

**Comment by mean-ui-thread** [comment]
Do you need anything else from me for merging this pull request? it looks like the CI for it might be stuck...

Right now,  my team is manually patching `.hunter/_Base/Download/Hunter/0.24.16/09668c2/Unpacked/cmake/modules/hunter_sanity_checks.cmake` by hand because we much prefer using Ninja Multi-Config, It's not ideal but it will do for now.

**Comment by rbsheth** [comment]
Sorry for the delay here. Merged!

**Comment by NeroBurner** [comment]
released: https://github.com/cpp-pm/hunter/releases/tag/v0.24.18

**Pull request merged**
