### PR TITLE
OpenSSL: Fix build on universal windows platforms, add UWP job to global build matrix

### PR DESCRIPTION
**Pull request by Dargun**
disable forbidden fibers

* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/create/cmake.html)
  step by step carefully. **[Yes|No]**

* My change will allow compile OPENSSL for windows universal platforms

---

* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html)
  step by step carefully. **[Yes|**

---

* I've checked this [Git style guide](https://0.readthedocs.io/en/latest/git.html). **[Yes|No]**
* I've checked this [CMake style guide](https://0.readthedocs.io/en/latest/cmake.html). **[Yes|No]**
* My change will work with CMake 3.2 (minimum requirement for Hunter). **[Yes|No]**
* I will try to keep this pull request as small as possible and will try not to mix unrelated features. **[Yes|No]**

---

### CODE REVIEW

**Comment by NeroBurner** [comment]
please add a UWP based CI Job to the CI matrix, that the packages can be checked against UPW the future (just one for amd64 should be enough I think)

**Comment by Dargun** [comment]
How can i add new CI jobs?

**Comment by NeroBurner** [comment]
The default pipelines are in https://github.com/cpp-pm/hunter/blob/master/.github/workflows/ci/matrix.json

You may (I don't really know) have to update the https://github.com/cpp-pm/hunter/blob/master/.github/workflows/ci/build.cmd file as well

The project specific overrides are at `cmake/projects/<project>/ci/matrix.json`. For example the Boost one is at: https://github.com/cpp-pm/hunter/blob/master/cmake/projects/Boost/ci/matrix.json

**Comment by Dargun** [comment]
windows store version should be added to default pipelines or?

**Comment by Dargun** [comment]
i added a ci folder with copy of default matrix and one append.
but now all pipelines failing with error 
> [hunter ** INTERNAL **] HUNTER_<name>_VERSION can't be empty
what i'am did wrong?

**Comment by Dargun** [comment]
is there way to abort a pending job 
> https://github.com/cpp-pm/hunter/actions/runs/3183247090

he will never fidn a image with Os windows-2017

**Comment by NeroBurner** [comment]
I think @rbsheth can kill those, I can't

I meant for you to update the default pipeline for all projects, to test in the future all packages against the UWP pipeline

**Comment by rbsheth** [comment]
> I think @rbsheth can kill those, I can't
> 
> I meant for you to update the default pipeline for all projects, to test in the future all packages against the UWP pipeline

Looks like it failed already, so I can't cancel it.

**Comment by Dargun** [comment]
> I think @rbsheth can kill those, I can't
> 
> I meant for you to update the default pipeline for all projects, to test in the future all packages against the UWP pipeline
i was following the docu
https://hunter.readthedocs.io/en/latest/creating-new/test/ci.html#override-default-tests
> Don’t copy and modify the default matrix

but for it makes also more sense to make uwp as standard.
i need to know what is the right way ;)

**Comment by Dargun** [comment]
> > I think @rbsheth can kill those, I can't
> > I meant for you to update the default pipeline for all projects, to test in the future all packages against the UWP pipeline
> 
> Looks like it failed already, so I can't cancel it.

yea seems after  1d 3h 41m 0s the timeout was comming

**Comment by NeroBurner** [comment]
> but for it makes also more sense to make uwp as standard.

what do you mean with this? I'm against making uwp the standard of Windows msvc builds, as not everyone (at least not me) is building against uwp. uwp CI builds should be an additional CI-job

**Comment by Dargun** [comment]
> > but for it makes also more sense to make uwp as standard.
> 
> what do you mean with this? I'm against making uwp the standard of Windows msvc builds, as not everyone (at least not me) is building against uwp. uwp CI builds should be an additional CI-job

sorry i meant with " but for me it makes also more sense to make uwp as standard." to add an uwp pipeline to 
"hunter\.github\workflows\ci\matrix.json" so that in future also uwp is allways tested.

**Comment by Dargun** [comment]
Question is for me do we want first test uwp only against openssl package or against all packages. i don't know if all packages are ready for compiling with uwp pipeline.

**Comment by NeroBurner** [comment]
the pipelines are used as status indicator. If the new UWP pipeline fails for a package we get some information about the package we haven't had before.

So yes, modify the default pipeline, such that we have a UWP pipeline for all packages

**Review by NeroBurner — CHANGES_REQUESTED** [review]
I think vs15 2017 isn't supported by GitHub-Actions anymore, you need to migrate to vs16-2019 at least

**Comment by Dargun** [comment]
> I think vs15 2017 isn't supported by GitHub-Actions anymore, you need to migrate to vs16-2019 at least

then i have to creeate a new pipeline script in polly or where are the scripts are comming from?

**Comment by NeroBurner** [comment]
The other CI Jobs are already migrated to vs16-2019, just use those

or are there specific polly scripts for UWP, which aren't updated for vs-16-2019 yet?

**Comment by Dargun** [comment]
> The other CI Jobs are already migrated to vs16-2019, just use those
> 
> or are there specific polly scripts for UWP, which aren't updated for vs-16-2019 yet?

they are specific for UWP. 
Which branch is used from polly for hunter currently?

**Comment by Dargun** [comment]
is someone able to accept that merge request in the polly repro?
https://github.com/cpp-pm/polly/pull/15

**Comment by rbsheth** [comment]
> is someone able to accept that merge request in the polly repro? [cpp-pm/polly#15](https://github.com/cpp-pm/polly/pull/15)

done now!

**Comment by Dargun** [comment]
don't understand why is not finding that pipeline script
> build.py: error: argument --toolchain: invalid choice: 'vs-16-2019-win64-store-10-cxx17''

**Comment by Dargun** [comment]
it seems the toolchain needs to be also added to toolchain_table.py in polly repro
i made a merge request in polly repro.
> https://github.com/cpp-pm/polly/pull/16

**Comment by Dargun** [comment]
Can i manually restart these checks or do i need to make a new dummy commit?

**Comment by NeroBurner** [comment]
I think on github you need to add a new dummy commit. Don't exactly know, but that would be the fastest/easiest route for you

**Comment by NeroBurner** [comment]
It seems hunter needs to be updated to pass the `-A x64` flag for the Win64 VS16 build (and newer VS17 builds as well). Don't know why it only happens for the store build though

https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2016%202019.html

**Comment by NeroBurner** [comment]
Maybe the polly project needs to be updated, as the error message comes from it: https://github.com/cpp-pm/polly/blob/bc01aedc9fa8e591c85007afb9eb6340be889b2e/utilities/polly_init.cmake#L18

**Comment by Dargun** [comment]
i made a fix for that in polly. seems i made wrong copy paste :(
https://github.com/cpp-pm/polly/pull/18

**Comment by NeroBurner** [comment]
please modify your branch such that you're using your personal fork of polly, so that you don't have to wait for us to merge polly changes

when you're ready (working uwp toolchain) please ping me again

**Comment by Dargun** [comment]
don't get why he is not using x64 
> Please change generator to: Visual Studio 16 2019 Win64
(Current generator: Visual Studio 16 2019)

on my local testing all works without issue.
but i don't use the python workflow, may i need to add somthing more there?

**Comment by Dargun** [comment]
> It has probably something to do with how polly does things, and maybe a check with isn't up to date with the newer way of handling the generator toolset generator architecture flags
> 
> to fix this eather do local testing or see my recommendation above

yea i made now the local test with own forks of polly and hunter with
> python jenkins.py

now i realized that in polly if i use vs15
> polly_init(
    "Visual Studio 15 2017 Win64 / ${CMAKE_SYSTEM_NAME} ${CMAKE_SYSTEM_VERSION} / ZW"
    "Visual Studio 15 2017 Win64"
)

this Win64 needs to be added to second paramter but for  vs16 without Win64

> polly_init(
    "Visual Studio 16 2019 Win64 / ${CMAKE_SYSTEM_NAME} ${CMAKE_SYSTEM_VERSION} / C++17"
    "Visual Studio 16 2019"
)

but it needs to inlcude a flag instead Win64 in polly_init

> include("${CMAKE_CURRENT_LIST_DIR}/flags/vs-platform-x64.cmake")

don't understand that different logic, but then it works.

**Comment by rbsheth** [comment]
> i fixed that on polly. [cpp-pm/polly#19](https://github.com/cpp-pm/polly/pull/19)

Merged this

**Comment by NeroBurner** [comment]
The current Error has nothing to do with the UWP changes. I think this is a transient error. Could you try to trigger the pipeline again to see if the error persists?
```
 -- Using src='https://github.com/openssl/openssl/archive/OpenSSL_1_1_1o.tar.gz'
  CMake Error at C:/__BIN/NkECa/OpenSSL/OpenSSL-prefix/src/OpenSSL-stamp/download-OpenSSL.cmake:170 (message):
    Each download failed!
```

**Comment by Dargun** [comment]
Failed to connect to codeload.github.com port 443 after 21024 ms: Timed out ?

**Comment by Dargun** [comment]
> The current Error has nothing to do with the UWP changes. I think this is a transient error. Could you try to trigger the pipeline again to see if the error persists?
> 
> ```
>  -- Using src='https://github.com/openssl/openssl/archive/OpenSSL_1_1_1o.tar.gz'
>   CMake Error at C:/__BIN/NkECa/OpenSSL/OpenSSL-prefix/src/OpenSSL-stamp/download-OpenSSL.cmake:170 (message):
>     Each download failed!
> ```

kk

**Comment by Dargun** [comment]
Store version is now successful.
What is with the other failing jobs?

**Comment by NeroBurner** [comment]
You can see the failing and successful build status per package here: https://cpp-pm.github.io/hunter/

the status is collected after each merged PR and the site is updated

You're welcome to try to fix those build errors in a separate PR if you want :)

**Review by NeroBurner — APPROVED** [review]
New UWP based job is working, is this PR ready to be merged or do you want to still add something?

**Comment by Dargun** [comment]
> New UWP based job is working, is this PR ready to be merged or do you want to still add something?

Can be merged, there is nothing more to add.

**Comment by NeroBurner** [comment]
Thanks for taking the time and work though all those setbacks :)

**Comment by Dargun** [comment]
> Thanks for taking the time and work though all those setbacks :)

More time then expected, but now i know better the flow.
Thanks for your help ;)

**Comment by NeroBurner** [comment]
released: https://github.com/cpp-pm/hunter/releases/tag/v0.24.8

**Pull request merged**
