### PR TITLE
(Testing/Broke) Update Magnum to version 2019.10

### PR DESCRIPTION
**Pull request by caseymcc**
This requires: https://github.com/cpp-pm/hunter/pull/160

* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html)
  step by step carefully. **Yes**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/caseymcc/hunter/builds/31141588
  * https://travis-ci.org/caseymcc/hunter/jobs/656517179

* This update will add a few toolchains.
  They are included in this pull request: https://github.com/cpp-pm/hunter-testing/pull/50

### CODE REVIEW

**Comment by rbsheth** [comment]
@caseymcc Can you rebase onto the new master, which has the `corrade` update?

**Comment by caseymcc** [comment]
Yeah I will, but it currently has some other error that I have not had the chance to tracked down yet.

**Comment by rbsheth** [comment]
@caseymcc Still broken?

**Comment by caseymcc** [comment]
yeah, I will try and work on it a little today.

**Comment by caseymcc** [comment]
abandoning this, don't have time to find the issue.

**Pull request closed without merging**
