### PR TITLE
Update 'SDL2' package to v2.0.12-p0

### PR DESCRIPTION
**Pull request by drodin**
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html)
  step by step carefully. **[Yes]**

* This update will fix a few toolchains.
  - ios-nocodesign-13-2-dep-9-3
see below...

* I'll need a fork of https://github.com/libsdl-org/SDL (which is the new official SDL repository) in https://github.com/cpp-pm
I can see that there is already https://github.com/cpp-pm/SDL2 repo forked from hunter-packages,
but it is unchanged and not used for any version in cmake/projects/SDL2/hunter.cmake
Same goes for all other SDL_* repos, which I intend to update to new versions.
Can we delete (or rename and archive) those repos and re-fork from official ones?

There is also semi related problem which I want to mention here.
I can see that recent iOS tests are failing for all packages with the same error: '-- Detecting C compiler ABI info - failed' https://github.com/drodin/hunter/runs/2941173795#step:7:1131
I have this problem on my system also (apple m1, osx 11.1, cmake 19/20, Xcode 12.3), iOS builds failing.
It is this cmake issue https://gitlab.kitware.com/cmake/cmake/-/issues/19720
Adding *set(CMAKE_TRY_COMPILE_CONFIGURATION Release)* to polly iOS toolchain helps.
Should we update polly?

---

### CODE REVIEW

**Comment by rbsheth** [comment]
@drodin I copied the old repos to `cpp-pm` in case hunter-packages goes away and we need those old packages. Since the names are a bit different, I re-forked the new repo and made the release from your branch here: https://github.com/cpp-pm/SDL/archive/refs/tags/v2.0.12-p0.tar.gz

Do you want me to move new SDL_mixer/image/etc. branches into our current forks?

Happy to have a polly fix for iOS! Can you please make a PR against polly? Thanks!

**Comment by drodin** [comment]
@rbsheth I've changed the source of archive to point to cpp-pm SDL repo release.
Also created a pull request for polly.
I can't think of an elegant way to solve the problem with a name clash of SDL_mixer and SDL_ttf repos
All this SDL repos in hunter-packages are forks from some conversion of old SDL mercurial repo.
As for me I would prefer to rename existing cpp-pm repos, change links for releases in hunter (to not forget to change them later if hunter-packages cease to exist), make new forks from official libsd-org repos.

**Comment by rbsheth** [comment]
Cool, I moved the existing SDL2 repos to `_legacy`. Can you update the old links in Hunter to point to those for those older versions?

https://github.com/cpp-pm/SDL2_legacy
https://github.com/cpp-pm/SDL_mixer_legacy
https://github.com/cpp-pm/SDL_ttf_legacy
https://github.com/cpp-pm/SDL_image_cmake_legacy

Here are the proper forks:
https://github.com/cpp-pm/SDL (done already here)
https://github.com/cpp-pm/SDL_mixer
https://github.com/cpp-pm/SDL_ttf
https://github.com/cpp-pm/SDL_image

**Comment by drodin** [comment]
@rbsheth I've updated links for SDL, though hashes are changed when you rename a repo (didn't thought about that)
meanwhile I have a problem with cached 'opusfile' package which is a dependency of 'SDL_mixer' see https://github.com/cpp-pm/hunter/issues/421
to mitigate problem I've created a pr in 'opusfile' repo to just up a version in hunter later,
this of course doesn't solve the problem in general

**Comment by rbsheth** [comment]
> @rbsheth I've updated links for SDL, though hashes are changed when you rename a repo (didn't thought about that)
> meanwhile I have a problem with cached 'opusfile' package which is a dependency of 'SDL_mixer' see #421
> to mitigate problem I've created a pr in 'opusfile' repo to just up a version in hunter later,
> this of course doesn't solve the problem in general

Thanks! Yeah hashes changing is annoying...

As far as the issue goes, changing `CMAKE_ARGS` and not affecting the cache mechanism seems like a bug. We'll have to look into it.

**Comment by rbsheth** [comment]
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.23.309

**Pull request merged**
