### PR TITLE
WIP: Adding Package SWIG

### PR DESCRIPTION
**Pull request by Waarbubble**
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/create/cmake.html)  step by step carefully. *Yes*

I am trying to add the swig package to the hunter package management

### CODE REVIEW

**Comment by Waarbubble** [comment]
Could someone give me access to run the github actions for this merge request

**Comment by rbsheth** [comment]
@Waarbubble I gave you access to run the actions.

**Comment by Waarbubble** [comment]
Nice, but this seems to be a continues problem until i make my first pull request has been merged

**Comment by rbsheth** [comment]
> Nice, but this seems to be a continues problem until my first pull request has been merged

Sorry, that's pretty annoying 😞

**Comment by NeroBurner** [comment]
any updates on this?

The CI jobs should also run on your personal fork of the project. Once it runs on your end we only need to run it once here to verify

**Comment by Waarbubble** [comment]
> any updates on this?
> 
> The CI jobs should also run on your personal fork of the project. Once it runs on your end we only need to run it once here to verify

I gave up working on this, as i can't seem to figure out what goes wrong. And the time vs. benefit for my project didn't seem to add up anymore.

**Comment by NeroBurner** [comment]
sorry to hear that

closing PR as stale/no-further-work

**Pull request closed without merging**
