### PR TITLE
Update 'pip_numpy' to v1.17.5

### PR DESCRIPTION
**Pull request by hjmallon**
* I've followed [this guide](https://cpp-pm-hunter.readthedocs.io/en/latest/creating-new/update.html)
  step by step carefully. **[Yes]**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/hjmallon/hunter/builds/29881159
  * https://travis-ci.org/hjmallon/hunter/builds/632380393

This change is blocked on #120 and #117 being merged. I have done 1.17.5 rather than 1.18.0 as that was what I needed, bu it should be dead easy now to add any number of other versions.

### CODE REVIEW

**Comment by rbsheth** [comment]
#120 and #117 both merged

**Comment by hjmallon** [comment]
Rebased and unblocked. I assume when this goes in a testing merge is made in `hunter-testing/pkg.pip_numpy`? I'm not sure whether I need to update or close the testing PR https://github.com/cpp-pm/hunter-testing/pull/31?

**Comment by rbsheth** [comment]
@hjmallon I need to update pkg.template with this change and then you can merge into that branch in hunter-testing.

**Comment by rbsheth** [comment]
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.23.242

**Comment by rbsheth** [comment]
Branch `pkg.template` has been updated https://github.com/cpp-pm/hunter-testing

**Pull request merged**
