### PR TITLE
Update libjpeg-turbo to 2.0.90

### PR DESCRIPTION
**Pull request by hjmallon**
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html)
  step by step carefully. **[Yes]**

---

* No need for fork as cmake package files are included upstream
* Do not build static+shared by default (only static)

Release 2.0.90 is AKA 2.1 (beta1) https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/2.0.90

@rbsheth : I see that you are maintaining this for Hunter here https://github.com/cpp-pm/libjpeg-turbo/commits/hunter-2.0.3 . I don't think any of those commits (except the `-p0` first one) were ever released to hunter? I also cannot find the test results (either on github-pages or old pkg.libjpeg-turbo (which doesn't seem to exist?) to confirm whether this change breaks anything important.

NB: This new release does not fix the fact that `CMAKE_OSX_ARCHITECTURES` is not handled correctly (though I have a change for that upcoming).

### CODE REVIEW

**Comment by rbsheth** [comment]
Yeah, the main thing was since this is a drop-in replacement for libjpeg, it should produce the libjpeg targets and be able to act as a  substitute in the Hunter ecosystem. I think we'd still need a fork for that.

**Comment by hjmallon** [comment]
That PR looks very relevant! I guess we could have `libjpeg-turbo` be upstream and `jpeg` come from the fork though?

**Comment by rbsheth** [comment]
That makes sense. Since there's been a bunch of changes to the `libjpeg-turbo` CMake files, can you check if simply adding a flag like `EXPORT_AS_JPEG` to the CMakeLists would work? Then I can get rid of all my fork work.

**Comment by hjmallon** [comment]
> That makes sense. Since there's been a bunch of changes to the libjpeg-turbo CMake files, can you check if simply adding a flag like EXPORT_AS_JPEG to the CMakeLists would work? Then I can get rid of all my other fork work.

I guess you mean something like `target_link_libraries(X JPEG::jpeg)`, rather than `target_link_libraries(X libjpeg-turbo::jpeg-static`. If so that is not implemented upstream yet, see:

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/CMakeLists.txt#L596
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/CMakeLists.txt#L1511

**Comment by rbsheth** [comment]
> > That makes sense. Since there's been a bunch of changes to the libjpeg-turbo CMake files, can you check if simply adding a flag like EXPORT_AS_JPEG to the CMakeLists would work? Then I can get rid of all my other fork work.
> 
> I guess you mean something like `target_link_libraries(X JPEG::jpeg)`, rather than `target_link_libraries(X libjpeg-turbo::jpeg-static`. If so that is not implemented upstream yet, see:
> 
> https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/CMakeLists.txt#L596
> https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/CMakeLists.txt#L1511

Hmm okay, we can update the `libjpeg-turbo` package but not the substitute for libjpeg version.

**Review by rbsheth — APPROVED** [review]

**Comment by rbsheth** [comment]
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.23.299

**Pull request merged**
