### PR TITLE
Add support for iOS simulator only builds

### PR DESCRIPTION
**Pull request by hjmallon**
* I've checked this [Git style guide](https://0.readthedocs.io/en/latest/git.html). **[Yes]**
* I've checked this [CMake style guide](https://0.readthedocs.io/en/latest/cmake.html). **[Yes]**
* My change will work with CMake 3.2 (minimum requirement for Hunter). **[Yes]**
* I will try to keep this pull request as small as possible and will try not to mix unrelated features. **[Yes]**

---

NB: This PR is based on top of my other one so will need rebasing when that one merges!

This PR fixes building iOS simulator only builds (which could be used to support arm64 macOS machines with iOS smulator). Such a toolchain is similar to `ios-nocodesign-arm64.cmake` from polly, but with the following changes.

```diff
diff --git a/ios-nocodesign-arm64.cmake b/ios-nocodesign-arm64.cmake
index c5a7216..5a2b4df 100644
--- a/ios-nocodesign-arm64.cmake
+++ b/ios-nocodesign-arm64.cmake
@@ -30,9 +30,12 @@ set(CMAKE_MACOSX_BUNDLE YES)
 
 include("${CMAKE_CURRENT_LIST_DIR}/flags/ios_nocodesign.cmake")
 
-set(IPHONEOS_ARCHS arm64)
-set(IPHONESIMULATOR_ARCHS "")
+set(IPHONEOS_ARCHS "")
+set(IPHONESIMULATOR_ARCHS "arm64;x86_64")
 
 include("${CMAKE_CURRENT_LIST_DIR}/compiler/xcode.cmake")
 include("${CMAKE_CURRENT_LIST_DIR}/os/iphone.cmake")
 include("${CMAKE_CURRENT_LIST_DIR}/flags/cxx14.cmake")
+
+set(CMAKE_OSX_SYSROOT "iphonesimulator" CACHE STRING "System root for iOS" FORCE)
+set(CMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH NO CACHE STRING "")
```

There are other bugs in this area in other Hunter schemes, but they will need addressing one by one. Search for `IPHONESIMULATOR_ARCHS` and `IPHONEOS_ARCHS` and look for places where Hunter assumes `arm64` means `arm64/device` rather than `arm64/simulator` to find them.

### CODE REVIEW

**Comment by NeroBurner** [comment]
As I'm not in the Apple ecosystem, could you explain what the variables mean (or did mean before your change, and now with this PR)? And why architectures can be an empty string?

- `IPHONEOS_ARCHS`
- `IPHONESIMULATOR_ARCHS`

**Comment by hjmallon** [comment]
All Apple embedded platforms have simulator environments provided with Xcode. So for `iphoneos` we have `iphonesimulator` and there is similar for watchOS and tvOS. When CMake makes a Makefile it has to choose one or the other (by setting `CMAKE_OSX_SYSROOT` to `iphonesimulator` for example. When CMake uses the Xcode generator it is able to build one project file which can then build the device binaries by defauult, but can be used to build simulator binaries as well (see https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html?highlight=cross%20compile#id29).

A normal setup (circa 2 years ago) would have been like Polly's [ios-nocodesign.cmake](https://github.com/cpp-pm/polly/blob/master/ios-nocodesign.cmake).

In that toolchain we have (for recent iOS versions):

```cmake
  set(IPHONEOS_ARCHS arm64)
  set(IPHONESIMULATOR_ARCHS x86_64)
```

These variables are Polly/Hunter specific and are used to set up variables in Xcode to make it possible to build `arm64-device` binaries (using `cmake --build ..` or `x86_64-simulator` binaries (using `cmake --build ... -- -sdk iphonesimulator`).

So `IPHONEOS_ARCHS` is the archs supported for iOS devices and `IPHONESIMULATOR_ARCHS` is the archs supported for the simulator.

When setup with `IPHONEOS_ARCHS` and `IPHONESIMULATOR_ARCHS`, Hunter uses a CMake mode `CMAKE_IOS_INSTALL_COMBINED` which adds special rules to the install where it builds the device binary, installs that, builds the simulator binary, and uses `lipo` to squash them into one file.

Polly toolchain [ios-nocodesign-arm64.cmake](https://github.com/cpp-pm/polly/blob/master/ios-nocodesign-arm64.cmake) shows a toolchain which does not setup simulator binaries at all. Hunter would not have used `CMAKE_IOS_INSTALL_COMBINED` here.

`CMAKE_IOS_INSTALL_COMBINED` cannot work correctly with both arm64-device and arm64-simulator binaries, so going forwards (unless/until CMake add lots of support for some other Apple xcframework stuff) we will have to have separate simulator and device builds.

The logic before this commit was to use `CMAKE_IOS_INSTALL_COMBINED` if there were architectures defined in the `IPHONESIMULATOR_ARCHS`. However to support iOS simulator only builds we need to change that to be if `IPHONESIMULATOR_ARCHS` and `IPHONEOS_ARCHS` are defined.

We could also add a `ios-nocodesign-simulator-universal2.cmake` toolchain to Polly for instance.

**Comment by hjmallon** [comment]
@NeroBurner : Rebase onto master after my other MR was merged. This should now be good to go. Thanks

**Review by NeroBurner — APPROVED** [review]

**Comment by NeroBurner** [comment]
released: https://github.com/cpp-pm/hunter/releases/tag/v0.24.8

**Pull request merged**
