### PR TITLE
Update 'CURL' to v8.4.0

### PR DESCRIPTION
**Pull request by hjmallon**
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html)
  step by step carefully. **[Yes]**

---

This required redoing the CMake integration in https://github.com/cpp-pm/curl/pull/6

### CODE REVIEW

**Comment by NeroBurner** [comment]
seems to work as well as the previous version

https://cpp-pm.github.io/hunter/#CURL

curl hunter test matrix

nice clean commits, one for each dependency. I've not checked the previous implementation, but if your new one does the same thing then it looks very good

**Comment by hjmallon** [comment]
There are probably things missing from it, but the old stuff was so confusing about what is required that I figured starting from here might make sense. Hopefully some other users of CURL in hunter can try it out and see if anything is missing.

**Comment by rbsheth** [comment]
Had trouble with newer versions of cURL in Hunter in the past, hope this fixes it!

**Comment by hjmallon** [comment]
@rbsheth @NeroBurner : Anything we can do to move this along? i.e. get https://github.com/cpp-pm/curl/pull/6 merged?

**Comment by rbsheth** [comment]
Merged and released your cURL changes: https://github.com/cpp-pm/curl/releases/tag/v7.88.1-p0

**Comment by hjmallon** [comment]
> Merged and released your cURL changes: https://github.com/cpp-pm/curl/releases/tag/v7.88.1-p0

Thanks, I have rebased, tested and updated this MR now

**Comment by hjmallon** [comment]
I have put a PR in for the latest CURL too (since I am in the area) https://github.com/cpp-pm/curl/pull/7

**Comment by rbsheth** [comment]
https://github.com/cpp-pm/curl/releases/tag/v8.4.0-p0

**Comment by hjmallon** [comment]
Thanks, this is now all ready on 8.4.0

**Review by NeroBurner — APPROVED** [review]

**Comment by NeroBurner** [comment]
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.25.2

**Pull request merged**
