### PR TITLE
aws-sdk-cpp: Fix link pointing to wrong fork

### PR DESCRIPTION
**Pull request by hjmallon**
* I've checked this [Git style guide](https://0.readthedocs.io/en/latest/git.html). **[Yes|]**
* I've checked this [CMake style guide](https://0.readthedocs.io/en/latest/cmake.html). **[Yes]**
* My change will work with CMake 3.2 (minimum requirement for Hunter). **[Yes]**
* I will try to keep this pull request as small as possible and will try not to mix unrelated features. **[Yes]**

---

Sorry @NeroBurner I should have labelled the other MR as 'do not merge until the upstream MR is merged and I have updated the links'. 😄

### CODE REVIEW

**Review by NeroBurner — APPROVED** [review]
my brain diff comparison overlooked that little tidbit :sweat_smile: Thanks for the correction!

**Comment by hjmallon** [comment]
Is there a plan for a release tag soon?

**Comment by NeroBurner** [comment]
sure, why not ;)

released: https://github.com/cpp-pm/hunter/releases/tag/v0.24.8

**Comment by hjmallon** [comment]
Thanks!

**Pull request merged**
