### PR TITLE
Boost 1.75.0 without mingw update

### PR DESCRIPTION
**Pull request by thomassuckow**
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html)
  step by step carefully. **Yes**

### CODE REVIEW

**Comment by thomassuckow** [comment]
Alright. I have made sure this fails the same ways 1.72 did so I'm going to call this equivalent. I know there is a PR for 1.74 trying to address this but 1.75 resolves issues with Boost:iostreams and crosscompiling so I think it is worth at least getting the update.

**Comment by rbsheth** [comment]
FYI @Bjoe

**Review by rbsheth — APPROVED** [review]

**Comment by rbsheth** [comment]
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.23.289

**Comment by Bjoe** [comment]
Hm I see. unfortunately, the android stuff is missing :-)... I will do this.

**Pull request merged**
