### PR TITLE
update ci toolchains

### PR DESCRIPTION
**Pull request by drodin**
Having this recently in Actions:
The ubuntu-16.04 environment is deprecated and will be removed on September 20, 2021. Migrate to ubuntu-latest instead. For more details see https://github.com/actions/virtual-environments/issues/3287

Maybe it's also a good time to review toolchains list. I would personally like to update ios, osx ones at least.

### CODE REVIEW

**Comment by rbsheth** [comment]
> I would personally like to update ios, osx ones at least.

Let's do it?

**Comment by drodin** [comment]
@rbsheth I've updated osx/ios toolchains to newer ones, this needs https://github.com/cpp-pm/polly/pull/12 to be merged
test run https://github.com/drodin/hunter/actions/runs/1083200090

**Comment by hjmallon** [comment]
Maybe need to update the Boost ones too?

**Comment by rbsheth** [comment]
> Maybe need to update the Boost ones too?

In another PR?

**Review by rbsheth — APPROVED** [review]

**Pull request merged**
