### PR TITLE
Update LehrFEM++ to 0.8.0

### PR DESCRIPTION
**Pull request by craffael**
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html)
  step by step carefully. **Yes**

### CODE REVIEW

**Comment by craffael** [comment]
Should I uncomment all the toolchains that didn't work in ci?

**Comment by rbsheth** [comment]
> Should I comment all the toolchains that didn't work in ci?

Nah, having the failed ones shown is useful for https://cpp-pm.github.io/hunter/

Of course, fixing them is preferred 😄

**Comment by craffael** [comment]
Thanks for the fast reply 😄 

> 
> Of course, fixing them is preferred 😄
I wish LehrFEM++ would support all these toolchains.
Well fixing them is quite hard because LehrFEM++ requires full C++17 compliance and more or less recent compilers (https://craffael.github.io/lehrfempp/getting_started.html).

I would suggest to merge it like that.

**Comment by rbsheth** [comment]
Ok 👍

**Comment by rbsheth** [comment]
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.23.295

**Pull request merged**
