### PR TITLE
Add a Universal2 macOS target to CI

### PR DESCRIPTION
**Pull request by hjmallon**
* I've checked this [Git style guide](https://0.readthedocs.io/en/latest/git.html). **[Yes]**
* I've checked this [CMake style guide](https://0.readthedocs.io/en/latest/cmake.html). **[Yes]**
* My change will work with CMake 3.2 (minimum requirement for Hunter). **[Yes]**
* I will try to keep this pull request as small as possible and will try not to mix unrelated features. **[Yes]**

---

I assume this is how I do it? Fixes https://github.com/cpp-pm/hunter/issues/385

### CODE REVIEW

**Comment by hjmallon** [comment]
I have no idea how to force this branch to retest a couple of projects to test it. As you can see above I tried putting some random changes in the project files but it didn't seem to work. Please could someone kick off manual GitHub runs for the Boost ones and some random cmake on (say ZLIB?) just to make sure this works correctly?

**Comment by rbsheth** [comment]
@hjmallon You need to edit a file in the project directory for CI to trigger (for example, `cmake/projects/ZLIB/hunter.cmake`)

**Comment by hjmallon** [comment]
Ah, I get this issue "strategy produced more than 256"

https://github.com/cpp-pm/hunter/actions/runs/771521571

**Comment by hjmallon** [comment]
Oh it worked here https://github.com/hjmallon/hunter/runs/2411416211?check_suite_focus=true !

I'll try Boost

**Comment by hjmallon** [comment]
@rbsheth : It is now done, I had to do some Boost thinning and setting the Xcode version to one with the 11.0 SDK

**Review by rbsheth — APPROVED** [review]
Great, thanks!

**Comment by rbsheth** [comment]
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.23.300

**Pull request merged**
