### PR TITLE
Update 'benchmark' to v1.5.0

### PR DESCRIPTION
**Pull request by chfast**
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html)
  step by step carefully. **[Yes]**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/chfast/hunter/builds/30285204
  * https://travis-ci.org/chfast/hunter/builds/640459295

* This update will break few old toolchains. TODO
  They are excluded in this pull request: https://github.com/cpp-pm/hunter-testing/pull/<number>

### CODE REVIEW

**Comment by chfast** [comment]
Rebasing `pkg.benchmark` before this would be nice.

There is also a bug report by clang analyzer. It has been fixed in https://github.com/google/benchmark/commit/51d991f1d7e6b28b8280d44606c28e121df23db0, but the 1.5.0 release still contains it.

**Comment by rbsheth** [comment]
@chfast Are you preparing a testing PR for this?

**Comment by chfast** [comment]
> @chfast Are you preparing a testing PR for this?

Not actively right now, but I can give it another try today or tomorrow.
What is the best way to disable a build (clang analyzer will need to be disabled for this release version).

**Comment by rbsheth** [comment]
Cool. You should comment out the failing toolchain in `.travis.yml` or `appveyor.yml` in your PR to hunter-testing. See https://hunter.readthedocs.io/en/latest/creating-new/create/cmake.html#excluding-tests

**Pull request merged**
