### PR TITLE
WIP Update Catch to 2.11.3

### PR DESCRIPTION
**Pull request by kaihowl**
* I've followed [this guide](https://hunter.readthedocs.io/en/latest/creating-new/update.html)
  step by step carefully. **Yes**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed": 

  * https://ci.appveyor.com/project/kaihowl/hunter/builds/31607508
  * https://travis-ci.com/github/kaihowl/hunter/builds/154290029
    * Failed due to https://github.com/catchorg/Catch2/issues/1862

* This update will break few old toolchains. 
  * Awaiting discussion on https://github.com/catchorg/Catch2/issues/1862 to decide if I exclude the ios toolchain

### CODE REVIEW

**Comment by rbsheth** [comment]
@kaihowl Still WIP?

**Comment by kaihowl** [comment]
@rbsheth Yes. This needs a PR against ingenue / CI to disable the broken toolchain. I was hoping to hear from upstream instead of having to disable the toolchain. Since there was no reply, I will go ahead and create the PR to disable the broken toolchain.

**Comment by kaihowl** [comment]
PR open in hunter-testing#54

**Comment by rbsheth** [comment]
> PR open in [cpp-pm/hunter-testing#54](https://github.com/cpp-pm/hunter-testing/pull/54)

Merged!

**Pull request closed without merging**
