### PR TITLE
Add OpenBLAS 0.3.7

### PR DESCRIPTION
**Pull request by xsacha**
* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/update.html)
  step by step carefully. **Yes**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":
N/A

Easy one to start with. Upstream change only. Latest version.

### CODE REVIEW

**Comment by bkotzz** [comment]
Looks good, but I still think we should make sure we run CI on every package and/or version that gets added to hunter. I think that’s one of the really nice things of hunter - that you can pull in any of the packages and you know for sure that it will *at least* build on all of the platforms that CI is being run on for that package. I really would like to find a better solution for running CI than the current setup, but in the meantime can we still use the existing setup, and merge/push the CI branch for this package and make sure everything still passes? https://github.com/ingenue/hunter/tree/pkg.openblas

**Comment by xsacha** [comment]
Ok, we using ingenue still?

**Comment by bkotzz** [comment]
I think for this case let’s still use ingenue. As soon as we need to make a change to that repo, we’ll need to fork it to the new org, but should be fine for this case. 

And I totally agree with you - I think that’s the first thing we want to change as maintainers. Stay tuned - I’ll write up a proposal tomorrow hopefully, and we’ll go from there. Ideally what we want is the relevant builds to run on this PR, rather than needing separate repos, branches and pushes

**Comment by rbsheth** [comment]
Released: https://github.com/cpp-pm/hunter/releases/tag/v0.23.215

**Pull request merged**
